# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20171215_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
